---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: test
  image: trion/ng-cli-karma:7.3.7
  commands:
  - npm install
  - ng test --watch=false --progress=false
  - ng e2e

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-backend
    auto_tag: true

- name: docker-arm
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-backend
    auto_tag: true
    auto_tag_suffix: -arm

---
kind: signature
hmac: 7cb8d98f20170fdc2c64104994b25ad6e0d176c944b0a0dd204432af242781d5

...
