clone:
  git:
    image: plugins/git
    skip_verify: true


pipeline:

  test:
    image: trion/ng-cli-karma:7.3.7
    commands:
      - npm install
      - ng test --watch=false --progress=false
      - ng e2e

  docker:
    image: docker
    privileged: true
    commands:
      - IMAGE_NAME="registry.plt.et.tu-dresden.de/pfe-ree-viz"
      - BRANCH_TEMP=$${DRONE_BRANCH/develop/latest}
      - DOCKER_IMAGE="$IMAGE_NAME:$${BRANCH_TEMP/master/stable}$${DRONE_TAG}"
      - DOCKER_IMAGE_ARM="$DOCKER_IMAGE-arm"
      - docker build -t $DOCKER_IMAGE .
      - docker build -f Dockerfile.arm -t $DOCKER_IMAGE_ARM .
      - docker push $DOCKER_IMAGE
      - docker push $DOCKER_IMAGE_ARM
      - docker image rm $DOCKER_IMAGE $DOCKER_IMAGE_ARM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch:
        - develop
        - master
      event:
        - tag
        - push

  notify:
    image: drillster/drone-email
    host: mail.zih.tu-dresden.de
    username: mgraube
    password: $EMAIL_PASSWORD
    secrets: [ email_password ]
    from: markus.graube@tu-dresden.de
    recipients: [ markus.graube@tu-dresden.de ]
    when:
      status: [ changed, failure ]
