---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: test
  image: trion/ng-cli-karma:8.0.2
  commands:
  - npm install
  - ng test --watch=false --progress=false
  - ng e2e

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-frontend
    auto_tag: true

- name: docker-arm
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-frontend
    auto_tag: true
    auto_tag_suffix: arm

---
kind: signature
hmac: 7a8d142b050b6d23338f17494910b850fe602c0450e36f2ec7d8f3356a411cbf

...
